### Table
Numpy
- [1. 행렬 데이터 생성](#행렬-데이터-생성)
- [2. 행렬 모양 변경하기](#행렬-모양-변경하기)
- [3. 행렬 데이터 선택](#행렬-데이터-선택)
- [4. 데이터 수정](#데이터-수정)
- [5. 조건으로 선택](#조건으로-선택)

# Numpy
- 데이터는 행렬로 표현
- 행렬 데이터 빠르게 계산해야 함
- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성

In [41]:
import numpy as np

### 행렬 데이터 생성
- ndarray : 한가지 데이터타입만 저장할 수 있는 배열

In [12]:
np.array((1, 2, 3)),type(np.array((1, 2, 3))) 

(array([1, 2, 3]), numpy.ndarray)

In [9]:
array2 = np.array(
    [[1, 2, 3],
     [4, 5, 6]],
)

In [11]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 2차원, 2행x3열
array2.ndim, array2.shape

(2, (2, 3))

### 행렬 모양 변경하기

In [14]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 행렬 데이터 선택
- offset index : masking

In [15]:
array2[1]

array([4, 5, 6])

In [16]:
array2[1][2]

6

In [19]:
array2[1][::-1]

array([6, 5, 4])

In [21]:
array2[1, 2] == array2[1][2]

True

### 데이터 수정

In [23]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [26]:
# 브로드캐스팅
array2[0] = 0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [27]:
array2[0] = [7, 8, 9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

### 조건으로 선택

In [28]:
array2 > 7

array([[False,  True,  True],
       [False, False,  True]])

In [29]:
idx = array2 > 7 #masking
array2[idx] # true만 남는다

array([ 8,  9, 10])

In [30]:
array2[idx] = 100  # masking = True인 성분만 100으로 바꾼다
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

### 행렬 데이터의 생성 2

In [31]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
data.dtype

dtype('float64')

In [34]:
data2 = data.astype("int")
data2.dtype

dtype('int64')

In [35]:
data2

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
data3 = np.ones((2, 3, 2))
data3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [39]:
# arange - range()와 동일함
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
np.arange(2, 10, 5)

array([2, 7])