In [2]:
import numpy as np

# Takeways
- Do not use rank-1 array
- Use `(n, 1)` column vector or `(1, n)`row vector
- Double check your matrix dimension / array size using `assert (a.shape==(n, m))`
- Use `a.reshape(n, m)` to make matrices you want

## Avoid `(n,)` shape
- `np.random.rand(5)`
    - rank 1 array

In [5]:
 a = np.random.randn(5) # don't use!

In [6]:
a

array([ 0.56176502, -1.42423893,  0.02103884,  0.76900328,  0.29266928])

In [7]:
a.shape

(5,)

In [10]:
a.T

array([ 0.56176502, -1.42423893,  0.02103884,  0.76900328,  0.29266928])

In [8]:
a.T.shape

(5,)

In [9]:
np.dot(a, a.T) # inner product

3.0215004534243435

## Create `(n, m)` shape
- `np.random.rand(5, 1)`
- `np.random.rand(1, 5`

In [11]:
a = np.random.rand(5, 1)

In [12]:
a # column vector 5 by 1

array([[0.80514962],
       [0.15746987],
       [0.15545572],
       [0.22063326],
       [0.11265457]])

In [17]:
a.shape

(5, 1)

In [15]:
a.T  # row vector 1 by 5

array([[0.80514962, 0.15746987, 0.15545572, 0.22063326, 0.11265457]])

In [18]:
a.T.shape

(1, 5)

In [16]:
np.dot(a, a.T) #outer product

array([[0.64826591, 0.12678681, 0.12516512, 0.17764278, 0.09070378],
       [0.12678681, 0.02479676, 0.02447959, 0.03474309, 0.0177397 ],
       [0.12516512, 0.02447959, 0.02416648, 0.0342987 , 0.0175128 ],
       [0.17764278, 0.03474309, 0.0342987 , 0.04867903, 0.02485534],
       [0.09070378, 0.0177397 , 0.0175128 , 0.02485534, 0.01269105]])

## small trick: check matrix shape
- `assert (a.shape == (5, 11))`
- convert 'rank 1 arrray' into 'col/row vector'!

In [19]:
# convert rank 1 array to legit vector
np.random.rand(5).reshape(1, 5) # rank1 array to column vector

array([[0.21199879, 0.77527993, 0.5153232 , 0.91681189, 0.14074119]])

In [20]:
np.random.rand(5).reshape(5, 1) # rank1 array to row vector

array([[0.85643637],
       [0.62192009],
       [0.07277455],
       [0.49335896],
       [0.96619533]])

### Test Operation

In [3]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [6]:
a

array([[-0.73393972, -1.04008438, -0.8958126 ],
       [ 1.09484727, -1.44660096, -1.10801904]])

In [7]:
b

array([[ 0.52628708],
       [-0.5203336 ]])

In [4]:
c

array([[-0.20765264, -0.5137973 , -0.36952552],
       [ 0.57451367, -1.96693455, -1.62835263]])

In [5]:
c.shape

(2, 3)

In [28]:
a = np.random.randn(3, 4) 
b = np.random.randn(4, 1)
c = a.T + b

In [29]:
a

array([[-0.4509939 , -0.35674227, -0.15687675,  0.28746718],
       [-0.86369472, -0.82923299, -0.45947909,  1.19271903],
       [ 0.75445521,  0.1925518 , -0.65509743,  1.19074704]])

In [30]:
a.T

array([[-0.4509939 , -0.86369472,  0.75445521],
       [-0.35674227, -0.82923299,  0.1925518 ],
       [-0.15687675, -0.45947909, -0.65509743],
       [ 0.28746718,  1.19271903,  1.19074704]])

In [31]:
b

array([[ 0.26830204],
       [-0.17234481],
       [-0.42500818],
       [ 0.43382217]])

In [32]:
c

array([[-0.18269186, -0.59539268,  1.02275724],
       [-0.52908708, -1.00157779,  0.02020699],
       [-0.58188493, -0.88448727, -1.08010561],
       [ 0.72128936,  1.6265412 ,  1.62456921]])

In [33]:
a + b.T

array([[-0.18269186, -0.52908708, -0.58188493,  0.72128936],
       [-0.59539268, -1.00157779, -0.88448727,  1.6265412 ],
       [ 1.02275724,  0.02020699, -1.08010561,  1.62456921]])

### Element-wise multiplication

In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)

In [16]:
a

array([[ 2.17756881,  0.407583  ,  1.50983384],
       [ 0.74558522, -0.32790774,  1.04873381],
       [-0.73434531, -0.04113262,  0.27134036]])

In [17]:
b

array([[-1.4855246 ],
       [-0.89116198],
       [-0.85991653]])

In [23]:
np.hstack([b,b,b])

array([[-1.4855246 , -1.4855246 , -1.4855246 ],
       [-0.89116198, -0.89116198, -0.89116198],
       [-0.85991653, -0.85991653, -0.85991653]])

In [21]:
a * np.hstack([b,b,b])

array([[-3.23483203, -0.60547457, -2.24289531],
       [-0.66443721,  0.29221891, -0.9345917 ],
       [ 0.63147567,  0.03537062, -0.23333006]])

In [22]:
c

array([[-3.23483203, -0.60547457, -2.24289531],
       [-0.66443721,  0.29221891, -0.9345917 ],
       [ 0.63147567,  0.03537062, -0.23333006]])

In [25]:
a[1][1] * np.hstack([b,b,b])[1][1] == c[1][1]

True

In [26]:
a[2][2] * np.hstack([b,b,b])[2][2] == c[2][2]

True

In [27]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 