In [1]:
import numpy as np

# 오차제곱합
$$E = \frac{1}{2}\sum^n_{i=1}(y_i-\hat{y}_i)^2$$

In [130]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
len(y), len(t)

(10, 10)

In [135]:
def sum_squares_error(y, t):
    #return np.sum((np.array(y)-np.array(t))**2)
    return np.sum((np.array(y)-np.array(t))**2)/2.0

In [136]:
sum_squares_error(y, t)

0.09750000000000003

# binary cross entropy

$$-\frac{1}{m}\sum^m_{i=1}{y_i \text{ln}(p_i)+(1-y_i)\text{ln} (1-p_i)}$$

In [121]:
def cross_entropy(Y, p):
    Y = np.array(Y)
    p = np.array(p)
    #print(len(p.ravel()))
    if len(p) > 1:
        return -1*np.sum(Y*np.log(p)+(1-Y)*np.log(1-p), axis=1) / len(p[0].flatten())
    else:
        return -1*np.sum(Y*np.log(p)+(1-Y)*np.log(1-p))

In [122]:
P = [[0.6, 0.2, 0.9, 0.3], [0.7, 0.9, 0.2, 0.4]]
Y = [[1., 1., 0., 0.], [1., 1., 0., 0.]]
cross_entropy(Y, P)

array([1.19488089, 0.29900116])

In [123]:
y_true = [[0., 1.], [0., 0.]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]
cross_entropy(y_true, y_pred)

array([0.91629073, 0.71355818])

In [113]:
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.losses import Reduction

In [124]:
y_true = [[0., 1.], [0., 0.]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]
# Using 'auto'/'sum_over_batch_size' reduction type.
bce = BinaryCrossentropy(reduction = Reduction.NONE)
bce(y_true, y_pred).numpy()

array([0.9162905 , 0.71355796], dtype=float32)