In [1]:
import numpy as np

In [2]:
def NAND(x1, x2):
    #w1 = 0.6
    #w2 = 0.6
    #theta = 0.8
    
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.2
    
    #temp = x1 * w1 + x2 * w2
    temp = np.dot(x, w) + b
    #print(temp)
    
    if temp < 0:
        return 0
    # theta와 같거나 크면
    else:
        return 1

In [3]:
for x in [(0,0), (0,1), (1,0), (1,1)]:
    y = AND(x[0], x[1])
    print(x, y)

NameError: name 'AND' is not defined

In [8]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    
    #temp = x1 * w1 + x2 * w2
    temp = np.dot(x, w) + b
    #print(temp)
    
    if temp < 0:
        return 0
    # theta와 같거나 크면
    else:
        return 1

In [9]:
for x in [(0,0), (0,1), (1,0), (1,1)]:
    y = OR(x[0], x[1])
    print(x, y)

(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 1


In [10]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    return NAND(s1, s2)

In [11]:
for x in [(0,0), (0,1), (1,0), (1,1)]:
    y = XOR(x[0], x[1])
    print(x, y)

(0, 0) 0
(0, 1) 0
(1, 0) 0
(1, 1) 0


In [14]:
def sigmoid(x):
    return 1/(1 + np.exp(-1*x))

In [15]:
x = np.array([-1.0, 1.0, 2.0])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [27]:
def relu(x):
    return np.maximum(0, x)

In [28]:
x = np.array([2, 1, -1])
relu(x)

array([2, 1, 0])

In [37]:
X = np.array([7, 3])
W = np.array([[1, 3, 5], [2, 4, 6]])
Y = np.dot(X.T, W)
Y

array([13, 33, 53])

# Layer1

In [43]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [44]:
X.shape, W1.shape, B1.shape

((2,), (2, 3), (3,))

In [52]:
A1 = np.dot(X, W1)+B1
A1

array([0.3, 0.7, 1.1])

# Layer2

In [48]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [53]:
Z2 = np.dot(sigmoid(A1), W2) + B2
Z2

array([0.51615984, 1.21402696])

# Layer3

In [59]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(sigmoid(Z2), W3) + B3
y = A3
y

array([0.31682708, 0.69627909])

# MLP

In [70]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['B1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['B3'] = np.array([0.1, 0.2])
    return network


def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['B1'], network['B2'], network['B3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2, W3) + b3
    y = a3 # output
    return y

In [71]:
test_net = init_network()
X = np.array([1.0, 0.5])
forward(test_net, X)

array([0.31682708, 0.69627909])

# Softmax

$$Softmax(x_i) = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [94]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

In [95]:
softmax([1,3,5])

array([0.01587624, 0.11731043, 0.86681333])

In [96]:
softmax([[1, 3, 5], [3, 10, 9]])

array([[8.96505747e-05, 6.62433126e-04, 4.89475553e-03],
       [6.62433126e-04, 7.26446131e-01, 2.67244597e-01]])

In [97]:
def softmax(x):
    sum_exp_x = np.sum(np.exp(x), axis=-1).reshape(-1, 1)
    return np.exp(x) / sum_exp_x

In [98]:
softmax([1,3,5])

array([[0.01587624, 0.11731043, 0.86681333]])

In [99]:
softmax([[1, 3, 5], [3, 10, 9]])

array([[1.58762400e-02, 1.17310428e-01, 8.66813332e-01],
       [6.66195022e-04, 7.30571551e-01, 2.68762254e-01]])