### Table
- [1. Quiz](#quiz)
- [2. Quiz2](#quiz-2)
- [3. Linspace & Logspace](#linspace-logspace)
- [4. Numpy Random](#numpy-random)
- [5. 행렬 데이터의 결합](#행렬-데이터의-결합)

### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray, np.array(iterable)
- 행렬의 생성 2 : ones, zeros
- 행렬 데이터 선택 : array[x, y, z] (바깥 차원에서 안쪽 차원으로)
- 행렬 데이터 수정
    - 행렬 데이터 선택
    - =, > (값(scala-broadcasting, vector, matrix))
    - 브로드 캐스팅 개념
- np.arange : list에서 사용하는 range : 결과가 ndarray 타입

### Quiz
- 100 ~ 130까지 랜덤한 숫자를 가지는 8*8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터

```
np.random.randint(100, 130, size=(8,8))
```

- 데이터 타입이 정수 -> 문자열 : ndarray.astype()

In [3]:
import numpy as np

In [4]:
random_matrix = np.random.randint(100, 130, size=(8,8))

In [25]:
def fiz_buz_fbz(num):
    if num % 3 == 0:
        if num % 5 == 0:
            return 'fbz'
        
        return 'fiz'
    
    elif num % 5 == 0:
        return 'buz'
    
    else:
        return np.random.randint(1, 100)

In [26]:
random_matrix

array([[108, 104, 110, 117, 100, 103, 105, 125],
       [118, 103, 102, 121, 110, 110, 121, 127],
       [121, 100, 104, 101, 107, 112, 124, 103],
       [107, 123, 110, 120, 107, 107, 100, 126],
       [119, 107, 128, 106, 113, 125, 125, 129],
       [108, 110, 116, 115, 111, 106, 120, 129],
       [102, 100, 111, 113, 113, 128, 115, 111],
       [112, 103, 110, 116, 113, 102, 116, 126]])

In [27]:
map(fiz_buz_fbz, random_matrix)

In [29]:
v_fiz_buz_fbz = np.vectorize(fiz_buz_fbz)
result = v_fiz_buz_fbz(random_matrix)
result

array([['fiz', '25', 'buz', 'fiz', 'buz', '64', 'fbz', 'buz'],
       ['43', '37', 'fiz', '90', 'buz', 'buz', '21', '72'],
       ['24', 'buz', '34', '60', '84', '50', '54', '27'],
       ['56', 'fiz', 'buz', 'fbz', '87', '5', 'buz', 'fiz'],
       ['97', '84', '58', '50', '58', 'buz', 'buz', 'fiz'],
       ['fiz', 'buz', '74', 'buz', 'fiz', '77', 'fbz', 'fiz'],
       ['fiz', 'buz', 'fiz', '64', '66', '3', 'buz', 'fiz'],
       ['12', '25', 'buz', '17', '39', 'fiz', '86', 'fiz']], dtype='<U3')

#### Mask Approach

In [45]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 True/False Mask Matrix 생성
index_3 = (random_matrix % 3 == 0)
index_5 = (random_matrix % 5 == 0)
index_15 = (random_matrix % 15 == 0)

In [46]:
# 데이터 타입을 str으로 변환
random_matrix_str = random_matrix.astype('str')

In [47]:
# True/False Mask matrix 이용하여 특정 조건 데이터를 선택 후 브로드캐스팅으로 값 대입
random_matrix_str[index_3] = 'fiz'
random_matrix_str[index_5] = 'buz'
random_matrix_str[index_15] = 'fbz'

In [48]:
random_matrix_str

array([['fiz', '104', 'buz', 'fiz', 'buz', '103', 'fbz', 'buz'],
       ['118', '103', 'fiz', '121', 'buz', 'buz', '121', '127'],
       ['121', 'buz', '104', '101', '107', '112', '124', '103'],
       ['107', 'fiz', 'buz', 'fbz', '107', '107', 'buz', 'fiz'],
       ['119', '107', '128', '106', '113', 'buz', 'buz', 'fiz'],
       ['fiz', 'buz', '116', 'buz', 'fiz', '106', 'fbz', 'fiz'],
       ['fiz', 'buz', 'fiz', '113', '113', '128', 'buz', 'fiz'],
       ['112', '103', 'buz', '116', '113', 'fiz', '116', 'fiz']],
      dtype='<U21')

### Quiz 2
- 1~20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드

In [50]:
data = np.random.randint(1, 20, (5, 5))

In [51]:
data

array([[ 8, 18,  4, 14, 14],
       [ 2,  9,  2, 17, 16],
       [19, 14, 10,  5, 16],
       [ 7, 19, 19,  8, 10],
       [ 3, 16, 10, 18,  2]])

In [59]:
index_max = (data == np.max(data))
index_min = (data == np.min(data))

In [60]:
data_str = data.astype('str')

In [61]:
data_str[index_max] = 'MAX'
data_str[index_min] = 'MIN'

In [62]:
data_str

array([['8', '18', '4', '14', '14'],
       ['MIN', '9', 'MIN', '17', '16'],
       ['MAX', '14', '10', '5', '16'],
       ['7', 'MAX', 'MAX', '8', '10'],
       ['3', '16', '10', '18', 'MIN']], dtype='<U21')

### linspace logspace
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [71]:
# linspace
np.linspace(0, 100, 5) # 0~100 구간을 선형적으로 5개 구간으로 등분할

array([  0.,  25.,  50.,  75., 100.])

In [65]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3) # 10^2 ~ 10^4 구간을 지수적으로 3개 구간 등분할

array([  100.,  1000., 10000.])

In [67]:
# 30세에 연봉이 $10000 이고 60세의 연봉이 $100000 일때
# 연봉이 선형으로 즈가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [68]:
age_30 = 10000
age_60 = 100000

#### 선형으로 증가

In [69]:
np.linspace(age_30, age_60, 4)

array([ 10000.,  40000.,  70000., 100000.])

#### 지수적으로 증가

In [73]:
np.logspace(np.log10(age_30), np.log10(age_60), 4) # 지수적으로 4개 구간 등분할

# 40세 : $21544
# 50세 : $46415
# 60세 : $100000

array([ 10000.        ,  21544.34690032,  46415.88833613, 100000.        ])

### numpy random
- seed : 랜덤 분포에 대한 설정값 (동일 시드에서 랜덤함수 출력 결과는 항상 실행할 때마다 동일)
- rand : 균등분포로 난수를 생성 (uniform, 모든 값이 출현할 확률 동일)
    - randint : 균등분포로 정수값 발생
- randn : 정규분포 (0, 1)로 난수를 생성 (평균값 0 부근일수록 출현확률 높음)
- shuffle : 행렬 데이터 섞기
- choice : 특정 확률로 데이터 선택

In [74]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

In [75]:
result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [77]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [78]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [80]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[4, 1, 1, 3],
       [9, 9, 3, 7],
       [6, 7, 7, 7]])

In [81]:
np.random.shuffle(r)

In [82]:
r

array([[9, 9, 3, 7],
       [6, 7, 7, 7],
       [4, 1, 1, 3]])

In [86]:
# choice
# range(5) 범위에서, 10번 뽑고, 확률 개별 지정 가능.
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([3, 2, 2, 2, 4, 4, 2, 0, 4, 2])

In [90]:
# unique
numbers, counts = np.unique(r, return_counts = True)
print(numbers)
print(counts)

{n:c for (n, c) in zip(numbers, counts)}

[1 3 4 6 7 9]
[2 2 1 1 4 2]


{1: 2, 3: 2, 4: 1, 6: 1, 7: 4, 9: 2}

### 행렬 데이터의 결합
- concatenate

In [92]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3= np.random.randint(10, size=(3, 3))

In [93]:
na1

array([[8, 5, 4],
       [2, 9, 7]])

In [94]:
na2

array([[1, 9],
       [2, 1],
       [0, 7]])

In [95]:
na3

array([[1, 8, 9],
       [0, 7, 0],
       [5, 2, 5]])

#### 세로결합

In [97]:
np.concatenate((na1, na3))

array([[8, 5, 4],
       [2, 9, 7],
       [1, 8, 9],
       [0, 7, 0],
       [5, 2, 5]])

#### 가로결합

In [99]:
np.concatenate((na2, na3), axis=1)

array([[1, 9, 1, 8, 9],
       [2, 1, 0, 7, 0],
       [0, 7, 5, 2, 5]])

In [100]:
# c
# 열+열 결합
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
# r_
# 행+행 결합
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])