# BoW

In [1]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [12]:
from collections import defaultdict
import numpy as np
# tokenizing

# doc_ls = []
# for doc in docs:
#     doc_ls.append(doc.split())

doc_ls = [doc.split() for doc in docs]

print(doc_ls)

# 사전 생성
word2id = defaultdict(lambda : len(word2id))

# for doc in doc_ls:
#     for token in doc:
#         word2id[token]

[word2id[token] for doc in doc_ls for token in doc]        
print(word2id)

# BoW
BoW = []
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
        
    BoW.append(bow.tolist())

print(BoW)
# [[1, 1, 1, 1, 0, 0, 0, 0], 
#  [1, 1, 0, 2, 1, 0, 0, 0], 
#  [0, 1, 0, 0, 0, 1, 2, 1]]

[['오늘', '동물원에서', '원숭이를', '봤어'], ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'], ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]
defaultdict(<function <lambda> at 0x7f9609b8d268>, {'오늘': 0, '동물원에서': 1, '원숭이를': 2, '봤어': 3, '코끼리를': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})
[[1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 0, 2, 1, 0, 0, 0], [0, 1, 0, 0, 0, 1, 2, 1]]


In [13]:
word2id.items()

dict_items([('오늘', 0), ('동물원에서', 1), ('원숭이를', 2), ('봤어', 3), ('코끼리를', 4), ('원숭이에게', 5), ('바나나를', 6), ('줬어', 7)])

In [18]:
import pandas as pd
from IPython.core import display as ICD

sorted_vocab = sorted((value, key) for key, value in word2id.items())
sorted_vocab

vocab = [v[1] for v in sorted_vocab]
vocab

for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW[i]], columns=vocab))
    print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   1      1     1   1     0      0     0   0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   1      1     0   2     1      0     0   0




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   0      1     0   0     0      1     2   1

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
count_vec = CountVectorizer()
BoW = count_vec.fit_transform(docs)
BoW.toarray()

array([[1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 2, 1, 0, 0, 0, 1],
       [1, 2, 0, 0, 0, 1, 1, 0]])

In [22]:
vocab = count_vec.get_feature_names()
vocab

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']

In [23]:
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
    print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   1   1     1      0   0     0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   2   1     0      0   0     1




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     2   0   0     0      1   1     0

In [29]:
import gensim
from gensim import corpora

doc_ls = [doc.split() for doc in docs]
doc_ls



[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [32]:
id2word = corpora.Dictionary(doc_ls)
# id2word.doc2bow(doc_ls[2])
BoW = [id2word.doc2bow(doc) for doc in doc_ls]
BoW

[[(0, 1), (1, 1), (2, 1), (3, 1)],
 [(0, 1), (1, 2), (2, 1), (4, 1)],
 [(0, 1), (5, 2), (6, 1), (7, 1)]]

In [40]:
id2word.keys()

[0, 1, 2, 3, 4, 5, 6, 7]

In [37]:
list(id2word.values())

['동물원에서', '봤어', '오늘', '원숭이를', '코끼리를', '바나나를', '원숭이에게', '줬어']

In [41]:
from gensim.matutils import sparse2full

vocab = id2word.values()
# vocab = [id2word[i] for i in id2word.keys()]


['동물원에서', '봤어', '오늘', '원숭이를', '코끼리를', '바나나를', '원숭이에게', '줬어']


In [42]:
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))], columns=vocab))
    print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  1.0  1.0   1.0   0.0   0.0    0.0  0.0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  2.0  1.0   0.0   1.0   0.0    0.0  0.0




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  0.0  0.0   0.0   0.0   2.0    1.0  1.0

# TDM

In [45]:
doc_ls = [doc.split() for doc in docs]

print(doc_ls)

# 사전 생성
word2id = defaultdict(lambda : len(word2id))

# for doc in doc_ls:
#     for token in doc:
#         word2id[token]

[word2id[token] for doc in doc_ls for token in doc]        
print(word2id)

# TDM
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
for i, doc in enumerate(doc_ls):    
    for token in doc:
        TDM[word2id[token], i] += 1
        
        
TDM

[['오늘', '동물원에서', '원숭이를', '봤어'], ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'], ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]
defaultdict(<function <lambda> at 0x7f95f08add08>, {'오늘': 0, '동물원에서': 1, '원숭이를': 2, '봤어': 3, '코끼리를': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})


array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [46]:
count_vec = CountVectorizer()
DTM = count_vec.fit_transform(docs)
TDM = DTM.toarray().T
TDM

array([[1, 1, 1],
       [0, 0, 2],
       [1, 2, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]])

# TF-IDF <br>
weighting schema|weight
--|--
tf (term frequency)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/91699003abf4fe8bdf861bbce08e73e71acf5fd4" />
idf(inverse document frequency) |<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/864fcfdc0c16344c11509f724f1aa7081cf9f657" />

In [71]:
# 사전 생성
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

doc_ls = [doc.split() for doc in docs]

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]        


DTM = np.zeros((len(doc_ls), len(word2id)), dtype=int)
for i, doc in enumerate(doc_ls):    
    for token in doc:
        DTM[i, word2id[token]] += 1
        
print(word2id)        


defaultdict(<function <lambda> at 0x7f95f019e7b8>, {'오늘': 0, '동물원에서': 1, '원숭이를': 2, '봤어': 3, '코끼리를': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})


In [61]:
def compute_DTM(docs):
    doc_ls = [doc.split() for doc in docs]

    word2id = defaultdict(lambda : len(word2id))
    [word2id[token] for doc in doc_ls for token in doc]        


    DTM = np.zeros((len(doc_ls), len(word2id)), dtype=int)
    for i, doc in enumerate(doc_ls):    
        for token in doc:
            DTM[i, word2id[token]] += 1
            
    return word2id, DTM

In [60]:
# TF
def compute_TF(DTM):
    doc_len = DTM.shape[0]
    word_len = DTM.shape[1]
    
    tf = np.zeros((doc_len, word_len))
    
    for doc_i in range(doc_len):
        for word_i in range(word_len):
            tf[doc_i, word_i] = DTM[doc_i, word_i]/DTM[doc_i].sum()
    
    return tf



compute_TF(DTM)

array([[0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.2 , 0.  , 0.4 , 0.2 , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.2 ]])

In [64]:
import math

# IDF
def compute_IDF(DTM):
    doc_len = DTM.shape[0]
    word_len = DTM.shape[1]
    
    idf = np.zeros(word_len)
    for i in range(word_len):
        idf[i] = -math.log10(np.count_nonzero(DTM[:, i])/doc_len)
    
    return idf

compute_IDF(DTM)

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [66]:
def compute_TFIDF(DTM):
    tf = compute_TF(DTM)
    idf = compute_IDF(DTM)
    
    tfidf = np.zeros(tf.shape)
    for doc_i in range(DTM.shape[0]):
        for word_i in range(DTM.shape[1]):
            tfidf[doc_i, word_i] = tf[doc_i, word_i] * idf[word_i]
            
    return tfidf

compute_TFIDF(DTM)

array([[ 0.04402281, -0.        ,  0.11928031,  0.04402281,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.03521825, -0.        ,  0.        ,  0.0704365 ,  0.09542425,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.        ,
         0.09542425,  0.1908485 ,  0.09542425]])

In [72]:
tf = compute_TF(DTM)
idf = compute_IDF(DTM)
tf * idf 

array([[ 0.04402281, -0.        ,  0.11928031,  0.04402281,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.03521825, -0.        ,  0.        ,  0.0704365 ,  0.09542425,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.        ,
         0.09542425,  0.1908485 ,  0.09542425]])

In [67]:
import pandas as pd

vocab = word2id.keys()
pd.DataFrame(compute_TFIDF(DTM), columns=vocab)

오늘  동물원에서     원숭이를        봤어      코끼리를     원숭이에게      바나나를        줬어
0  0.044023   -0.0  0.11928  0.044023  0.000000  0.000000  0.000000  0.000000
1  0.035218   -0.0  0.00000  0.070437  0.095424  0.000000  0.000000  0.000000
2  0.000000   -0.0  0.00000  0.000000  0.000000  0.095424  0.190849  0.095424

In [68]:
docs = ["The cat sat on my face I hate a cat", "The dog sat on my bed I love a dog"]
word2id, DTM = compute_DTM(docs)
vocab = word2id.keys()
pd.DataFrame(compute_TFIDF(DTM), columns=vocab)


The       cat  sat   on   my      face    I      hate    a       dog  \
0 -0.0  0.060206 -0.0 -0.0 -0.0  0.030103 -0.0  0.030103 -0.0  0.000000   
1 -0.0  0.000000 -0.0 -0.0 -0.0  0.000000 -0.0  0.000000 -0.0  0.060206   

        bed      love  
0  0.000000  0.000000  
1  0.030103  0.030103

# ifidf 2 <br>
weighting schema|weight|설명
--|--|--
tf(double normalization 0.5)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/45badc1c70ec2caa00ed8c21ed75bd9f8d3e650c" />|=0.5 + 0.5(토큰빈도/문서내최빈토큰)
idf(inverse document frequency smooth)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/25f4d6690acaaef1f15f308d24f6f8a439de971d" />|=log(문서갯수/(1+토큰빈도)) + 1

In [95]:
len([True, True])

2

In [85]:
'오늘 동물원에서 원숭이를 봤어'.count('오늘')

1

In [78]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

doc_ls = [doc.split() for doc in docs]

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]       

vocab = word2id.keys()

In [79]:
tfidf = np.zeros((len(doc_ls), len(vocab)))
tfidf
                 
                 

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
def count_token(token, doc):
    return doc.count(token)

In [88]:
def tf(token, doc):
    return 0.5 + 0.5 * count_token(token, doc) / max([count_token(w, doc) for w in doc])

In [89]:
def idf(token, docs):
    numerator = len(docs)
    denominator = 1 + len([True for doc in docs if token in doc])
    return math.log10(numerator/denominator) + 1

In [90]:
def tfidf_score(token, doc, docs):
    return tf(token, doc) * idf(token, docs)

In [91]:
for i in range(len(doc_ls)):
    for token in doc_ls[i]:
        tfidf[i, word2id[token]] = tfidf_score(token, doc_ls[i], doc_ls)

tfidf

array([[1.        , 0.87506126, 1.17609126, 1.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.75      , 0.65629595, 0.        , 1.        , 0.88206844,
        0.        , 0.        , 0.        ],
       [0.        , 0.65629595, 0.        , 0.        , 0.        ,
        0.88206844, 1.17609126, 0.88206844]])

In [92]:
pd.DataFrame(tfidf, columns=vocab)

오늘     동물원에서      원숭이를   봤어      코끼리를     원숭이에게      바나나를        줬어
0  1.00  0.875061  1.176091  1.0  0.000000  0.000000  0.000000  0.000000
1  0.75  0.656296  0.000000  1.0  0.882068  0.000000  0.000000  0.000000
2  0.00  0.656296  0.000000  0.0  0.000000  0.882068  1.176091  0.882068

In [96]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [116]:
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(docs)

In [117]:
tfidf.todense()

matrix([[0.3269504 , 0.        , 0.45951737, 0.45951737, 0.68614212,
         0.        , 0.        , 0.        ],
        [0.25581527, 0.        , 0.71907887, 0.35953944, 0.        ,
         0.        , 0.        , 0.53685707],
        [0.19095294, 0.80147238, 0.        , 0.        , 0.        ,
         0.40073619, 0.40073619, 0.        ]])

In [111]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

count_vectorizer = CountVectorizer()
DTM = count_vectorizer.fit_transform(docs)
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(DTM)
tfidf.todense()

matrix([[0.37311881, 0.        , 0.4804584 , 0.4804584 , 0.63174505,
         0.        , 0.        , 0.        ],
        [0.28680065, 0.        , 0.73861611, 0.36930805, 0.        ,
         0.        , 0.        , 0.48559571],
        [0.2344005 , 0.79374908, 0.        , 0.        , 0.        ,
         0.39687454, 0.39687454, 0.        ]])

In [112]:
count_vectorizer.get_feature_names()

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']

In [105]:
tfidf_vectorizer.vocabulary_

{'오늘': 3,
 '동물원에서': 0,
 '원숭이를': 4,
 '봤어': 2,
 '코끼리를': 7,
 '원숭이에게': 5,
 '바나나를': 1,
 '줬어': 6}

In [110]:
vocab = tfidf_vectorizer.get_feature_names()
vocab

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']

In [118]:
pd.DataFrame(tfidf.todense(), columns=vocab)

동물원에서      바나나를        봤어        오늘      원숭이를     원숭이에게        줬어  \
0  0.326950  0.000000  0.459517  0.459517  0.686142  0.000000  0.000000   
1  0.255815  0.000000  0.719079  0.359539  0.000000  0.000000  0.000000   
2  0.190953  0.801472  0.000000  0.000000  0.000000  0.400736  0.400736   

       코끼리를  
0  0.000000  
1  0.536857  
2  0.000000

In [114]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [115]:
import gensim
from gensim import corpora
from gensim.models import TfidfModel


In [121]:
doc_ls = [doc.split() for doc in docs]
id2word = corpora.Dictionary(doc_ls)
DTM = [id2word.doc2bow(doc) for doc in doc_ls]
model = TfidfModel(DTM)
tfidf = model[DTM]
tfidf

In [123]:
from gensim.matutils import sparse2full

vocab = [id2word[i] for i in id2word.keys()]
DTM_matrix = [sparse2full(doc, len(vocab)).tolist() for doc in tfidf]
pd.DataFrame(DTM_matrix, columns=vocab)

동물원에서        봤어        오늘     원숭이를      코끼리를      바나나를     원숭이에게        줬어
0    0.0  0.327185  0.327185  0.88651  0.000000  0.000000  0.000000  0.000000
1    0.0  0.569307  0.284654  0.00000  0.771272  0.000000  0.000000  0.000000
2    0.0  0.000000  0.000000  0.00000  0.000000  0.816497  0.408248  0.408248